name: Tests

on: 
    [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
      
    - name: MSBuild
      run: msbuild /t:restore /p:Configuration=ReleaseNuGet ColorPicker.sln
      
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
      
    - name: Pack
      run: nuget pack ColorPicker.nuspec -version 0.1.1
