name: Tests

on: 
    [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
      
    - name: MSBuild Restore x86
      run: msbuild /t:restore /p:Configuration=ReleaseNuGet /p:Platform="x86" ColorPicker.sln
      
    - name: MSBuild Build x86
      run: msbuild /p:Configuration=ReleaseNuGet /p:Platform="x86" ColorPicker.sln

    - name: MSBuild Restore x64
      run: msbuild /t:restore /p:Configuration=ReleaseNuGet /p:Platform="x64" ColorPicker.sln
      
    - name: MSBuild Build x64
      run: msbuild /p:Configuration=ReleaseNuGet /p:Platform="x64" ColorPicker.sln

    - name: MSBuild Restore ARM
      run: msbuild /t:restore /p:Configuration=ReleaseNuGet /p:Platform="ARM" ColorPicker.sln
      
    - name: MSBuild Build ARM
      run: msbuild /p:Configuration=ReleaseNuGet /p:Platform="ARM" ColorPicker.sln

    - name: MSBuild Restore ARM64
      run: msbuild /t:restore /p:Configuration=ReleaseNuGet /p:Platform="ARM64" ColorPicker.sln
      
    - name: MSBuild Build ARM64
      run: msbuild /p:Configuration=ReleaseNuGet /p:Platform="ARM64" ColorPicker.sln

    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
      
    - name: Pack
      run: nuget pack ColorPicker.nuspec
